version: '2'
services:
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
  video_service:
    image: spirogov/video_service
    links:
      - mysql
    ports:
      - "8086:8086"
