= Python 3 + Selene + Docker Tutorial
:toc: left
:toclevels: 4

*Author:* Sergey Pirogov

*Blog:* http://automation-remarks.com

== Requirements

- Python 3
- Docker
- Git

== Start system under test

Use **docker** and **docker-compose**

=== Download docker-compose.yml file

----
curl -O https://raw.githubusercontent.com/SergeyPirogov/python-video-service/master/docker-compose.yml
----

=== Start application

----
docker-compose up -d
----

Check application started at http://localhost:8086

== Create project

----
mkdir selene_demo
----

=== Install pipenv

Pipenv docs: https://github.com/kennethreitz/pipenv

```
pip install pipenv
```

=== Create project virtualenv with python 3 installed

```
pipenv --three
```

=== Activate virtualenv

```
pipenv shell
```

=== Required packages

- selene
- pytest
- pytest-allure-adapter
- pytest-env
- testcontainers

==== Install selene

Latest alfa release:

```
pip install selene --pre
```

Latest development:

```
pip install git+https://github.com/yashaka/selene.git
```

==== Install pytest

```
pip install pytest
```

==== Install pytest-env

```
pip install pytest-env
```

==== Install testcontainers

https://github.com/SergeyPirogov/testcontainers-python

Release version:

```
pip install testcontainers
```

Development version:

```
pip install git+https://github.com/SergeyPirogov/testcontainers-python.git
```

=== Open project in Pycharm

Create python packages **src** and **tests**.

Under **src** create python module package **pages**

Create file **pytest.ini**:

```
[pytest]
addopts = --tb=short -sv
env =
    selene_browser_name=chrome
    selene_base_url=http://localhost:8086
```

Start creation of page object modules under under **pages** package:

- login_page.py
- main_page.py

Describe page objects

==== Run tests in console

```
pytest -sv tests/
```

You can specify env variables:

```
selene_browser_name=chrome pytest -sv tests/
```

== Reports
=== Install Allure adaptor

```
pip install pytest-allure-adaptor
```

=== Allure v1

Install http://wiki.qatools.ru/display/AL/Allure+Commandline[Allure command line]

==== Generate report

```
allure generate <folder>
```

*Open generated report:*

=== Allure v2

```
pip install git+https://github.com/allure-framework/allure-python2.git@master#subdirectory=allure-python-commons
pip install git+https://github.com/allure-framework/allure-python2.git@master#subdirectory=allure-pytest
```

==== Generate report

Create run.sh in case of allure2:

```
#!/bin/bash
rm -rf report

mkdir -p report

rm -rf allure-report

pytest tests

allure_gen/bin/allure generate report
```

Run tests:

```
./run.sh
```

=== Travis integration

See file **.travis.yml** in the project root.

== Report portal integration

Report Portal is a service, it provides great capabilities for speeding up results
analysis and reporting by means of built-in analytical features.
Report Portal is the great addition to the
Continuous Integration and Continuous Testing process.
It seamlessly integrates with mainstream platforms such as Jenkins, Jira,
BDD process, majority of Functional and Unit testing frameworks.
Real-time integration allows to manage and track execution status directly from Report Portal.

http://reportportal.io/

=== Start Report portal

https://github.com/reportportal/reportportal

```
curl https://raw.githubusercontent.com/reportportal/reportportal/master/docker-compose.yml -o docker-compose.yml
```

```
docker-compose up -d
```

Check *http://ip:8080*

login\pass for access: *default\1q2w3e* and *superadmin\erebus*

=== Install RP adaptor

```
pip install pytest-reportportal
```

pytest.ini
```
[pytest]
rp_uuid = uid reportportal
rp_endpoint = http://ip:port
rp_project = video_portal
```

Run tests:

```
py.test ./tests
```

That's all! Thank you =)
